### ISSUE TITLE
Icon loading

### ISSUE THREAD

**Issue by zigzhang** [clemfeelsgood/Prynt#12]
Hey Todd,
Some problem loading the icon for Facebook, Instagram, Twitter, Reveal and Scan on my Chrome (also Firefox, but working fine on Safari)

![screen shot 2015-03-04 at 10 30 45 am](https://cloud.githubusercontent.com/assets/3306192/6480993/b66d61f0-c259-11e4-9174-48e6b18b40a5.png)
![screen shot 2015-03-04 at 10 33 52 am](https://cloud.githubusercontent.com/assets/3306192/6481024/0391ad06-c25a-11e4-9054-ccbc636a37ff.png)

**Comment by tfe** [comment]
When did it start doing that?

Sent from my iPhone

On Mar 4, 2015, at 1:39 AM, David <notifications@github.com> wrote:

Hey Todd,
Some problem loading the icon for Facebook, Instagram, Twitter, Reveal and
Scan on my Chrome (also Firefox, but working fine on Safari)

[image: screen shot 2015-03-04 at 10 30 45 am]
<https://cloud.githubusercontent.com/assets/3306192/6480993/b66d61f0-c259-11e4-9174-48e6b18b40a5.png>
[image: screen shot 2015-03-04 at 10 33 52 am]
<https://cloud.githubusercontent.com/assets/3306192/6481024/0391ad06-c25a-11e4-9054-ccbc636a37ff.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/clemfeelsgood/Prynt/issues/12>.

**Comment by zigzhang** [comment]
I didn't really check carefully the website until today. So I can't really say. Sorry

**Comment by tfe** [comment]
Can you look in the console for any indication the fonts didn't load, or any error messages? What URL are you on?

**Comment by zigzhang** [comment]
Yes:

Font from origin 'http://d1kk24s8modqpt.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.pryntcases.com' is therefore not allowed access.
(index):1 Resource interpreted as Font but transferred with MIME type application/font-sfnt: "http://d1kk24s8modqpt.cloudfront.net/production/assets/fontawesome-webfont-bcd7bf6d8d8a80ab0eed428bb4220282.ttf?v=4.2.0".

**Comment by tfe** [comment]
OK, looks like the Access-Control-Allow-Origin header is being set on the
TTF version of the font but not the WOFF. I’ll look into it.

**Comment by tfe** [comment]
OK, I made some changes to the CDN configuration. Let’s wait for those to
propagate and see if it helps.

**Comment by tfe** [comment]
Looks like Cloudfront is sending the right header now. Can you see if it works for you?

**Comment by zigzhang** [comment]
Working fine
