### ISSUE TITLE
Carousel (image loading)

### ISSUE THREAD

**Issue by zigzhang** [clemfeelsgood/Prynt#13]
Hi Todd,
Still problem loading the carousel

![screen shot 2015-03-06 at 5 51 13 pm](https://cloud.githubusercontent.com/assets/3306192/6529535/a7edf384-c429-11e4-9f4e-bc3bf261bd50.png)

**Comment by tfe** [comment]
I updated the version on the carousel plugin tonight; I think it may have helped. Can you confirm?

**Comment by zigzhang** [comment]
Still have the same problem.
Sometimes it loads, sometimes it doesn't :/ Most of the time it's when I return on the website after some time.

**Comment by tfe** [comment]
OK, tried something else. Let me know if you see any improvement.

**Comment by tfe** [comment]
Carousel is gone now; closing this out.
