### ISSUE TITLE
Staging website: background image

### ISSUE THREAD

**Issue by zigzhang** [clemfeelsgood/Prynt#14]
Hey Todd,

I have a problem with the size of the sections. When I click on Techy for example, I see a little bit of the next section. (See image). Could you check that please?

Thanks

![screen shot 2015-03-18 at 12 50 45 pm](https://cloud.githubusercontent.com/assets/3306192/6708106/a2295356-cd6d-11e4-9626-c90b7f47c6e2.png)

**Comment by tfe** [comment]
Now that you guys are using Asana, let’s file future issues through there to keep everything in one place.

In the case of this image, I'm not sure what you would like me to do. We could use a taller image if you want to send one. But if your browser window is that wide, the height is necessarily proportional.
