### ISSUE TITLE
Fixed position background images moving during scroll

### ISSUE THREAD

**Issue by tfe** [clemfeelsgood/Prynt#8]
In Chrome on David's mac.

**Comment by zigzhang** [comment]
This might help:
When I was on staging and the javascript didn't load (didn't have the titles of sections, and no carousel >> the images display one after another at the end), the fixed position worked well.
The problem might come from the Javascript

**Comment by tfe** [comment]
As an update on this, I worked on this quite a bit today. It seems to be a bug in Chrome's rendering engine, where having fixed-position elements (e.g. the text) inside of an element with an attached background will result in the background being displayed unattached in certain conditions (e.g. scrolling). It happens whether the JS is there or not; just in our case the JS is what shows the fixed position element.

I'm exploring alternatives to the current arrangement that may let us work around the bug.

**Comment by tfe** [comment]
Closing this; obviated by design refresh.
